name: Lock closed inactive issues

on:
  schedule:
    # Run at 16:00 every day
    - cron: '0 16 * * *'

jobs:
  lock_closed:
    if: github.repository == 'angular/angular'
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/lock-closed@2357f952775070b44dbc09363c4593d033b982b3
        with:
          lock-bot-key: ${{ secrets.LOCK_BOT_PRIVATE_KEY }}
